# Generated by Django 3.0.4 on 2020-05-01 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('room_num', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('check_in', models.DateTimeField(default=datetime.datetime.now)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=10000)),
            ],
        ),
    ]
